#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

    # add sources
    ctx.env.append_value('GLAD_SOURCES', ['src/glad.c'])

    # On windows we're looking for "opengl32"
    import sys
    if sys.platform == 'win32' or sys.platform == 'cygwin' or sys.platform == 'msys':
        ctx.check_cxx(lib='opengl32', uselib_store='opengl', mandatory=True)
        ctx.env.append_value('GLAD_LIB', ['opengl']);

        ctx.env.append_value('GLAD_SOURCES', ['src/glad_wgl.c'])
    else:
        ctx.check_cc(lib='m', uselib_store='m', mandatory=True)
        ctx.env.append_value('GLAD_LIB', ['m']);

        ctx.check_cc(lib='dl', uselib_store='dl', mandatory=True)
        ctx.env.append_value('GLAD_LIB', ['dl'])

        ctx.check_cxx(lib='GL', uselib_store='opengl', mandatory=True)
        ctx.env.append_value('GLAD_LIB', ['opengl']);

        ctx.env.append_value('GLAD_SOURCES', ['src/glad_glx.c'])

def build(ctx):
    ctx.stlib(source=ctx.env.GLAD_SOURCES,
              target='glad',
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.GLAD_LIB)
