#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

    # On windows we're looking for "opengl32"
    import sys
    if sys.platform == 'win32' or sys.platform == 'cygwin' or sys.platform == 'msys':
        ctx.check_cxx(lib='opengl32', uselib_store='opengl', mandatory=True)
    else:
        ctx.check_cxx(lib='GL', uselib_store='opengl', mandatory=True)

def build(ctx):
    ctx.stlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='glew',
              includes=['include'],
              export_includes=['include'],
              use=['opengl'])
