#ifndef ORANGE_INPUT
#define ORANGE_INPUT

namespace orange {
  // Enums
  namespace InputCode {
    namespace Key {
      enum Key {
        A = 4,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Enter,
        Escape,
        Delete,
        Tab,
        Space,
        Minus,
        Equals,
        LeftBracket,
        RightBracket,
        Backslash,
        Semicolon = 51,
        Quote,
        Grave,
        Comma,
        Period,
        Slash,
        Capslock,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PrintScreen,
        ScrollLock,
        Pause,
        Insert,
        Home,
        PageUp,
        DeleteForward,
        End,
        PageDown,
        Right,
        Left,
        Down,
        Up,
        KeyPadNumLock,
        KeyPadDivide,
        KeyPadMultiply,
        KeyPadSubtract,
        KeyPadAdd,
        KeyPadEnter,
        KeyPad1,
        KeyPad2,
        KeyPad3,
        KeyPad4,
        KeyPad5,
        KeyPad6,
        KeyPad7,
        KeyPad8,
        KeyPad9,
        KeyPad0,
        KeyPadPoint,
        NonUSBackslash,
        KeyPadEquals = 103,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        Help = 117,
        Menu,
        LeftControl = 224,
        LeftShift,
        LeftAlt,
        LeftGUI,
        RightControl,
        RightShift,
        RightAlt,
        RightGUI,
        Count
      };
    }

    namespace MouseButton {
      enum MouseButton {
        Left,
        Middle,
        Right,
        Extra1,
        Extra2,
        Extra3,
        Extra4,
        Extra5,
        Count
      };
    }
  }
}

#endif
