#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_cxx')

def configure(ctx):
    ctx.load('compiler_cxx')
    ctx.env.append_value('ORANGE_LIB', ['glew'])

    import sys
    print("Building for " + sys.platform)
    if sys.platform == 'win32' or sys.platform == 'cygwin' or sys.platform == 'msys':
        ctx.check_cxx(lib='winmm', uselib_store='winmm', mandatory=True)
        ctx.check_cxx(lib='gdi32', uselib_store='gdi32', mandatory=True)
        ctx.env.append_value('ORANGE_LIB', ['winmm', 'gdi32'])

    if sys.platform == 'linux':
        ctx.check_cxx(lib='X11', uselib_store='X11', mandatory=True)
        ctx.env.append_value('ORANGE_LIB', ['X11']);

    ctx.check_cxx(lib='pthread', uselib_store='pthread', mandatory=True)
    ctx.env.append_value('ORANGE_LIB', 'pthread')

def build(ctx):
    ctx.stlib(source=ctx.path.ant_glob('src/**/*.cpp'),
              target='orange',
              cxxflags=['-std=c++11'],
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.ORANGE_LIB)
